# pubspec.yaml
name: media_explorer_app
description: Ein privater Medien-Explorer mit lokalen und Server-Quellen.
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  photo_manager: ^2.7.0
  video_player: ^2.8.1
  cupertino_icons: ^1.0.2
  webdav_client: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
